apiVersion: apps/v1
kind: Deployment
metadata:
  name: qiji-message-deployment-test
  labels:
    app: qiji-message-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qiji-message-test
  template:
    metadata:
      labels:
        app: qiji-message-test
    spec:
      volumes:
      - name: public-dir
        hostPath:
          # 确保文件所在目录成功创建。
          path: /home/lighthouse/external_files/key
          type: DirectoryOrCreate
      - name: public
        hostPath:
          path: /home/lighthouse/external_files/key/public.key
          type: FileOrCreate
      containers:
      - name: qiji-message-test
        image: zhangzhulei/qiji-message-test
        args: [
          "--addr", ":80",
          "--auth_public_key_file", "/var/local/key/public.key",
          "--mysql_addr", "118.89.93.58:3306",
          "--ws_url", ":9090",
          "--rabbitmq_addr", "amqp://guest:guest@10.43.91.250:5672",
        ]
        ports:
        - containerPort: 80
          name: default
        - containerPort: 9090
          name: msg-websocket
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/local/key
          name: public-dir
        - mountPath: /var/local/key/public.key
          name: public
---
apiVersion: v1  
kind: Service  
metadata:  
  name: service-qiji-message-test
spec:  
  selector:  
    app: qiji-message-test
  type: NodePort
  ports:  
  - protocol: TCP  
    port: 80  
    targetPort: default
    name: default
  - protocol: TCP
    port: 9090
    targetPort: msg-websocket
    nodePort: 31001
    name: msg-websocket
    
